### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#100]
**Add a YouTube podcast** screen contain untranslatable string, see picture:

<img src="https://user-images.githubusercontent.com/37414585/150628556-180288ad-68af-4bd4-9ab4-246118056001.jpg" alt="https://user-images.githubusercontent.com/37414585/150628556-180288ad-68af-4bd4-9ab4-246118056001.jpg" width="200" height="400">

**Comment by gemiren** [comment]
Nice catch. Will add them soon. Thanks.

**Comment by oldman63** [comment]
Done.
