### ISSUE TITLE
Feature Request: Add Sorting Options (date/oldest to newest)

### ISSUE THREAD

**Issue by Bob-Builderson** [Podcast-Republic/PRApp#104]
PRAISE:
I love your app. It's honestly the best podcast app that I've used. More consistent than Podcast Addict, and a better feature set than Overcast. 

ISSUE:
One thing that I'm disappointed by is the inability to automatically sort playlists by age (or at all?)

EXAMPLE:
I'm trying to listen to two different podcast from old to new (This Week in Virology and This Week in Microbiology) but I don't want to have to drag the over 1,000 episodes manually in order of oldest to newest. 
I cannot also play them oldest to newest by podcast (great feature btw), because I want to play mutiple podcasts oldest to newest because the podcasts reference recent episodes. 

QUALIFICATION: 
If I'm actually just an idiot that can't figure out the obvious, fair enough. I'd love to have my ineptitude explained because I would get my solution as well as my weekly dose of shame. (Gotta keep my ego in check ✅)

SIGN OFF: 

Best wishes, 

Bob

PS  I've attached a very professional mock-up of the UI implementation
![Screenshot_20220128-161343__01](https://user-images.githubusercontent.com/59679367/151634677-42077c2b-52f4-41ac-9a7e-95d89dae5935.jpg)

**Comment by snarkywolverine** [comment]
Hey @Bob-Builderson - did you try the horizontal bar chart between the search (magnifying glass) and edit (pencil)?

**Comment by gemiren** [comment]
@Bob-Builderson, as @snarkywolverine said, have you tried the Sort options?
![Screenshot_1643467802](https://user-images.githubusercontent.com/7810771/151665556-dc5a481f-5f6f-439b-895f-0f77b79c3030.png)

**Comment by Bob-Builderson** [comment]
I actually did not see that at all. User error. Oops.

It's working perfectly. You all are amazing. Keep up the good work. 

Here's a picture of it working.
![Screenshot_20220129-160528](https://user-images.githubusercontent.com/59679367/151680396-4a3a3e83-0004-472f-a882-3ba26c84142d.jpg)
