### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#116]
Grouping

This function is how works? I don't see any change after activating it.

![Screenshot_20220213-085950_Podcast Republic](https://user-images.githubusercontent.com/3171626/153746090-ba253cec-b8d9-4f88-94fd-d0641ea40360.jpg)
![Screenshot_20220213-095525_Podcast Republic](https://user-images.githubusercontent.com/3171626/153746092-daff870f-80f7-4198-a23f-f2f94f4524cb.jpg)

**Comment by gemiren** [comment]
Have you set up the podcast priority in the podcast settings?

When grouping by podcast priority is enabled podcast priority will be used as the primary ordering and then the selected sorting criteria as the secondary ordering.

**Comment by oldman63** [comment]
> Have you set up the podcast priority in the podcast settings?
> 
> When grouping by podcast priority is enabled podcast priority will be used as the primary ordering and then the selected sorting criteria as the secondary ordering.

Oh, sorry.

Podcast priority != Playlist priority
:-)

**Comment by oldman63** [comment]
After opening #116 and two released versions still untranslated the

"Grouping"

Please importing translations.

**Comment by gemiren** [comment]
My bad. I merged the pull request but forgot to pull the changes. Will fix it in next update. Thanks.

**Comment by oldman63** [comment]
no problem, have a good day
