### ISSUE TITLE
[Question] Is Multi-thread download working?

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#137]
I've noticed that episodes from one podcast are downloading too slowly. I tried to download in PC with multi-threads. PR app is 10x slower like DL manager in PC. If multi-thread download is disabled the speed is the same.

Is multi-thread download working or not?

**Comment by gemiren** [comment]
The multi-threading means you can download multiple episodes simultaneously. It's still a single thread when downloading each episode.

**Comment by kubalav** [comment]
I thought it is multiple threads per one file.
