### ISSUE TITLE
Episodes/Title Display

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#165]
The text in the image cannot be localised at the moment, the source text is missing

![Screenshot_20221027_061735_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/198580318-2b068620-e11c-4753-82a4-9ce212aa616b.jpg)

**Comment by gemiren** [comment]
They are in the plurals.xml file under the same directory as the strings.xml file. Thanks.

**Comment by oldman63** [comment]
Thx, sorry
