### ISSUE TITLE
Increased fontsize system wide  - Wrong appearance

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#166]
System-wide font size increase - incorrect appearance in Podcast Republic

![Screenshot_20221028_134957_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/198580971-d1d7076f-5d80-406a-9df4-1472beaac8cd.jpg)

**Comment by gemiren** [comment]
Will fix that in next update. Thanks.
