### ISSUE TITLE
Search bar – cutted off titles

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#176]
I found issue related to recently bug in bottom panel. The same issue persists in search bar.
Look at this picture:

![search_bar-issue](https://user-images.githubusercontent.com/37414585/201601960-3b41a92f-2d2e-4685-a931-37f4c41f3260.jpg)

**Comment by gemiren** [comment]
Nice catch. Will get it fixed in the next update.

**Comment by kubalav** [comment]
@gemiren
I think you forget fix it.
