### ISSUE TITLE
The white strip in Dark theme

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#185]
I notice the white strip in Dark theme. Look at the picture below. If I change theme it disappears. After app restart it appears again.

![white_strip](https://user-images.githubusercontent.com/37414585/213105887-f160a0c5-6a40-4c58-b6d2-4009892618d1.png)

**Comment by gemiren** [comment]
Thanks very much for the bug report. It should have been fixed in the latest beta version 23.1.18b.

**Comment by kubalav** [comment]
Fixed.
