### ISSUE TITLE
Translated string is truncated

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#210]
`<string name="term_and_privacy_policy">"Feltételek és Adatvédelmi szabályzat"</string>`

![Screenshot_20230417_110414_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/232496514-2645f7f8-d13e-45a4-86c5-4eee39a00202.jpg)

**Comment by gemiren** [comment]
The text is formatted as a single line when used as the action buttons. Can we get a shorter transition? Thanks.
