### ISSUE TITLE
Translated string is truncated

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#220]
```
<string name="share">
<string name="playlist">
<string name="notes">
```

This happens in Ukrainian, Czech, Estonian and other translations. It is impossible to replace these words with a shorter synonym.
![1683449508136](https://user-images.githubusercontent.com/2944126/236667737-f15eb679-6e6f-4e4b-a379-1d5319dc4404.jpg)
![1683449508131](https://user-images.githubusercontent.com/2944126/236667738-69386def-ade5-49e0-a440-812b3011669e.jpg)
![1683449508124](https://user-images.githubusercontent.com/2944126/236667741-b80f94ca-65f3-481a-851f-1b4028e0a7d0.jpg)

**Comment by gemiren** [comment]
First of all, we should display the label in single line. Will get that fixed.

Regarding the long text in some translations, we probably have to live with that if we can't find a shorter text. What do you think?

Thanks!

**Comment by vlzuykov** [comment]
If you can't shorten the minimum distance between button labels, we'll have to use abbreviations.

**Comment by vlzuykov** [comment]
Recently there is a new text truncation
![Screenshot_2023-06-02-18-28-06-676-edit_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/03ecaba8-b40a-46f1-9e09-748db708e79d)

**Comment by gemiren** [comment]
Fixed in the latest beta. Thanks.
