### ISSUE TITLE
The notification either does not contain a cover or contains the cover of a previous episode

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#221]
The podcast artwork is always present in the Now playing screen, but not in the notification. Regardless of the value of the "use_embedded_artwork" setting. This applies to most podcasts. Sometimes the notification shows the artwork of the previous episode.
![1683623543982](https://user-images.githubusercontent.com/2944126/237050809-5ab9b72d-f53c-4a56-9662-876db0bae418.jpg)
![1683623543975](https://user-images.githubusercontent.com/2944126/237050820-6a070c11-c907-4672-b7b6-01d8ca94bda1.jpg)
![1683623543970](https://user-images.githubusercontent.com/2944126/237050824-f61c2a31-ad70-4f53-98dd-d0d742bde1b1.jpg)

**Comment by gemiren** [comment]
What's your Android version? Are you using the legacy media notification style? Thanks.

**Comment by vlzuykov** [comment]
Android 12. I am not using the legacy media notification style. Legacy notifications always displays correct artworks.

**Comment by vlzuykov** [comment]
Correction:
The notification **always** shows the artwork of the previous episode. And always does not show the artwork for the first episode in the playlist.

**Comment by gemiren** [comment]
The stock Android 12 media notification style should look like the attached screenshot. It doesn't use the artwork as the background of the notification. It looks like that your Android ROM uses a customized media notification style.

Anyway, let's get the app log. Please go to app Settings > About page to enable the Debug option. Then, please play anything to reproduce this notification issue. After that please go to the About page again to use the Report a bug button to send the app log. Hopefully the log can help track down this issue. 

Thanks.

**Comment by vlzuykov** [comment]
I found how to "fix" it. When the playback reaches the first chapter mark, the artwork used in notification changes from the artwork of the previous edpisode in the playlist to the artwork of the current episode. So if the playing episode doesn't have any predefined chapters, I can fix the artwork in the notification by adding a chapter to this episode.
