### ISSUE TITLE
UI bug on Now playing screen

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#222]
Sometimes when I opens Now playing screen it looks like this:
![1683623543988](https://user-images.githubusercontent.com/2944126/237052494-0fd9835a-d67e-46dd-a44c-e5e463d9bf20.jpg)

**Comment by gemiren** [comment]
Will get it fixed asap. Thanks.

**Comment by vlzuykov** [comment]
It looks like this issue had been resolved. I've not come across it a few weeks.

**Comment by gemiren** [comment]
Close it for now. Please reopen it if you can reproduce this issue. Thanks!
