### ISSUE TITLE
Indication of temporarily disabled playback speed

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#228]
When I enables 'Toggle playback speed on/off' option for the 'Shake your device' setting and actually shakes my device, playback speed is set to default but there is no visual indication of this on the Now Playing screen. The small window at the top of the screen still shows the custom speed value and the estimated time near the timeline bar still shows reduced negative time.
Maybe it's worth to add some indication of temporarily disabled playback speed? For example:
1. Change the displayed speed value to 1.0 or
2. Add some marks to this number.

**Comment by gemiren** [comment]
Yes, we should update the playback speed after the playback speed is changed. Will fix that in the next update. Thanks.
