### ISSUE TITLE
Incorrect sorting order of country names in some languages

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#236]
For languages whose alphabet is based on the Latin alphabet, the order of sorting the names of the countries, which is characteristic of the English language, is used. Therefore, for example, in the Czech-language interface, several country names that begin with letters that are not present in the English alphabet are at the end of the list.
![Screenshot_2023-06-03-13-11-39-945_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/dab07d84-66db-42a4-b53c-109eb16ddafd)
The same applies to the Ukrainian-language interface.  Several countries whose names begin with letters not present in the Russian alphabet are at the top of the list.
![Screenshot_2023-06-03-13-03-49-404_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/dafd3670-2a1d-4d15-9897-933ade172139)

**Comment by gemiren** [comment]
Will look into that. Thanks.

**Comment by vlzuykov** [comment]
All countries are now sorted by their English names regardless of the interface language. This is also an unnatural sort order for non-English languages

**Comment by gemiren** [comment]
Have you restarted the app after changing the language? The country/region names don't get updated after changing the language if the app is not restarted.

**Comment by vlzuykov** [comment]
Yes, I've restarted the app, then the language of the countries names have also changed, but not the order.
![Screenshot_2023-06-08-08-52-46-204_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/9730af3e-dcb3-440a-a032-679bf7655688)
In Czech countries names started with "S" should be before those are started with "T", but they are where the word "United" should be in English.
![Screenshot_2023-06-08-08-51-32-656_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/4ea35a58-0c09-4747-a1f1-833cbdd67e02)
Ukrainian list has the same order but different translation.
