### ISSUE TITLE
"episodes_have_been_added_to_playlist" has redundant punctuation

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#246]
When the user taps the "add one episod to playlist" button, the app adds string ": [%playlist_name]" at the end of string from `<plurals name="episodes_have_been_added_to_playlist">`.
The combined string look like this:
![Screenshot_2023-06-21-14-39-38-264-edit_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/df6b02d2-db10-4046-9e6d-d786e5a6d5e0)
A colon after a dot looks bad.
In the Ukrainian translation I would like to remove both dot and colon, and replace [ ] with « ». I don't think I can fix it myself, can I?

**Comment by gemiren** [comment]
That's a nice catch! I think we'd better to remove the playlist name completely from the message. What do you think? Thanks.

**Comment by vlzuykov** [comment]
I think this is the easiest way to fix it and it's acceptable. Trying to solve this problem another way leads to a more difficult question: what to do with adding an episode to multiple playlists, since the word "playlist" in this string is singular?
![IMG_20230621_190428](https://github.com/Podcast-Republic/PRApp/assets/2944126/7b3379b6-d881-4081-96a8-26ddd78c7a74)

**Comment by gemiren** [comment]
Good question. Android doesn't support plural strings with multiple parameters well, unfortunately. We'll leave it as it is for now.

**Comment by vlzuykov** [comment]
I think it should look like:
```html
    <plurals name="episodes_have_been_added_to_playlist">
        <item quantity="one">One episode have been added to selected playlists.</item>
        <item quantity="other">%1$d episodes have been added to selected playlists.</item>
    </plurals>
```  
or
```html
    <plurals name="episodes_have_been_added_to_playlist">
        <item quantity="one">One episode have been added to selected playlists: «%2$s»</item>
        <item quantity="other">%1$d episodes have been added to selected playlists: «%2$s»</item>
    </plurals>
``` where %2$s is the name of playlist.

**Comment by gemiren** [comment]
Let's use 'playlists'. Thanks.
