### ISSUE TITLE
Incorrect remaining time and repetitive noise

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#263]
Sometimes, at the very end of an episode listening the app displays incorrect remaining time at Now playing screen. This time passes through zero.
![IMG_20230706_210907](https://github.com/Podcast-Republic/PRApp/assets/2944126/3d17fc81-724b-48ad-aed9-2d18f2da51d9)

**Comment by vlzuykov** [comment]
If I press Jump to the next episode button at this stage (#254), the app shows 101% playing progress on this episode.
![Screenshot_2023-07-08-12-47-19-229-edit_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/c65820b7-9ff9-4913-834e-9b18e43b2f5c)

**Comment by gemiren** [comment]
Most likely the duration time retrieved from the downloaded podcast file is incorrect. Does this happen to that particular episode or all episodes of that podcast? Thanks.

**Comment by vlzuykov** [comment]
I don't know if all episodes of this podcast have this problem, but I can now say that many episodes of different podcasts, even most podcasts, have the same problem.
Another example. The last episode of [this podcast](https://anchor.fm/s/6c50fcb4/podcast/rss)  has duration 52:24 in both the feed and the file, but no less than 54:36 in this app.
![Screenshot_2023-07-08-14-16-59-592_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/77370880-5b49-4bb3-beeb-6f26cab77471)


![IMG_20230709_081834](https://github.com/Podcast-Republic/PRApp/assets/2944126/379c853a-9c67-41ba-9def-dbe5f9f668ee)

**Comment by vlzuykov** [comment]
It is stuck at the end of an episode with some repetitive noise that plays almost forever
https://youtu.be/nlJfXauwWDU

**Comment by vlzuykov** [comment]
This repetitive noise comes at the end of each episode

**Comment by vlzuykov** [comment]
This noise comes when playback speed is changed as well
https://youtube.com/shorts/nmylUbnBBQs?feature=share

**Comment by vlzuykov** [comment]
This reproduces again in the latest beta

**Comment by vlzuykov** [comment]
The noise at the end of an episode is fixed in the latest beta but noise when changing playback speed is still there.
