### ISSUE TITLE
enter_new_tag_name has two conflicting meanings

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#265]
enter_new_tag_name is used in both of the following cases:
![IMG_20230708_200642](https://github.com/Podcast-Republic/PRApp/assets/2944126/df4c2bae-9a05-40bb-8a03-13d990d22d13)
1. Enter a new name for the existing tag
2. Enter a name for the new tag

It's not that different in English, but it must be translated differently in some languages.

I suggest splitting this string into two, one for each of these use cases.

**Comment by gemiren** [comment]
Nice catch. Will split it into two strings. Thanks.
