### ISSUE TITLE
Incorrect sorting order of category names in some languages (fixed) + Incorrect alignment of elements in the list of categories

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#268]
Sorting order of category names has the same issue that was fixed for country names (#236).
![Screenshot_2023-07-11-20-21-34-949_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/6e500854-4ca0-423a-8235-27cdbfe52899)
And the list of categories also has weird alignment in many of the languages.
![IMG_20230711_203018](https://github.com/Podcast-Republic/PRApp/assets/2944126/03ac779b-a9b2-4ec6-b6d9-4d07cb6248a0)

**Comment by gemiren** [comment]
Nice catch. The genre name should be sorted based on the language used. Will get it fixed.

Regarding the alignment issue, I'm not able to reproduce on my side. Can you reproduce it?

Thanks!

**Comment by vlzuykov** [comment]
> Regarding the alignment issue, I'm not able to reproduce on my side. Can you reproduce it?

Yes. It seems that the names of some genres begin with a space symbol, but in fact this is not the case. I drew a red line to show this.

**Comment by vlzuykov** [comment]
![IMG_20230712_063143](https://github.com/Podcast-Republic/PRApp/assets/2944126/0b117fb2-ab36-47da-9749-5851805d1c57)
![IMG_20230712_063250](https://github.com/Podcast-Republic/PRApp/assets/2944126/ca726313-6f6d-4682-bd13-838be0f66b41)

**Comment by gemiren** [comment]
Will try harder to reproduce this issue and fix it asap. Thanks.

**Comment by vlzuykov** [comment]
> Regarding the alignment issue, I'm not able to reproduce on my side. Can you reproduce it?

It reproduces on my primary device but not on the other one.

**Comment by gemiren** [comment]
Interesting!

**Comment by vlzuykov** [comment]
What's even more interesting is that if i go to the Top Charts -> Category right after opening the Search tab, all elements on that Category tab are aligned nicely. The list of categories on the Search tab is always aligned nicely.
https://youtu.be/jG_MaBDQKBY
