### ISSUE TITLE
Auto download filter text issue

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#271]
Each keyword, even the last one, is followed by a comma and a space symbol.
![Screenshot_2023-07-12-14-01-11-464-edit_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/abd9b494-70ab-45bd-a426-2d548af4d7fb)
![Screenshot_2023-07-12-14-01-32-480-edit_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/19d8f4e5-c471-42b2-8133-b676d8be4e8b)

**Comment by gemiren** [comment]
Will fix that. Thanks.
