### ISSUE TITLE
Operations on zero elements

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#273]
It's allowed to mark 0 episodes as played or unplayed. The app doesn't show any messages like "No episodes available" when trying to do this.
![Screenshot_2023-07-12-14-24-09-888_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/48baa0ce-22dc-4aa1-a8eb-f4edc9845436)

**Comment by gemiren** [comment]
Will add the empty selections check. Thanks.
