### ISSUE TITLE
Incorrect sorting order of podcast names

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#280]
![IMG_20230717_214559](https://github.com/Podcast-Republic/PRApp/assets/2944126/f31ec174-f781-4bf7-8ea3-2fb132553c38)

Now the problem is a bit more complicated because the list of podcasts sorted by podcast name should be in the same order regardless of the language used in the app interface. Can you change that universal sorting rule so:
1. the words started with the Cyrillic letters "і" and "ї' are placed between "и" and "й"; 
2. the words started with the Cyrillic letter "є" are placed between "е" and "ж"; 
3. the words started with the Cyrillic letter "ґ' are placed between "г" and "д";
4. and some other letters in other languages?

**Comment by gemiren** [comment]
The app uses SQLite database and the sorting is done by SQLite. I don't think SQLite can sort in the natural language order. Thanks.
