### ISSUE TITLE
set_playlists is used in different contexts

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#281]
1. When selecting the "Add to the following playlists when adding an episode to a playlist" menu. It's OK.
2. When adding episode to playlists. Maybe it's worth to replace the set_playlists string by "Add to playlists" in this context?

**Comment by gemiren** [comment]
Nice catch. Will fix that. Thanks!

**Comment by vlzuykov** [comment]
And the third context: when long pressing Add to playlist button in the edit mode in the podcasts view.
![Screenshot_2023-07-19-17-13-22-802-edit_com itunestoppodcastplayer app](https://github.com/Podcast-Republic/PRApp/assets/2944126/fe86579a-9f54-472f-8523-5de023789767)
But when pressing this button the title changes to Add to playlists. Shoud this button add all unplayed episodes of selected podcasts to selected playlists?

**Comment by gemiren** [comment]
This button does two things:
1, it sets the default playlists of the selected podcasts.
2, it finds unplayed episodes of each podcast and then adds them to the selected playlists.
