### ISSUE TITLE
Messages are displayed below the screen

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#289]
This happens sometimes. I don't know how to reproduce it.
![Screenshot_2023-07-25-09-33-53-886-edit_com.itunestoppodcastplayer.app.jpg](https://github.com/Podcast-Republic/PRApp/assets/2944126/c85d6d09-4cf5-4183-afd9-d30256850f27)

**Comment by gemiren** [comment]
Will look into that and fix it asap. Thanks.
