### ISSUE TITLE
The timestamps near the timeline are unevenly aligned relative to the edges of the screen

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#290]
![IMG_20230725_111614](https://github.com/Podcast-Republic/PRApp/assets/2944126/e65fb867-b99b-4201-96d2-6c762bbbc5bb)
This happens on one of my devices.

**Comment by gemiren** [comment]
Will fix it in the next update. Thanks.

**Comment by vlzuykov** [comment]
This also reproduces again in the latest beta
