### ISSUE TITLE
Download filter doesn't seem to be working

### ISSUE THREAD

**Issue by bytesnz** [Podcast-Republic/PRApp#291]
The auto download filter doesn't seem to work as I expected. I have subscribed to the RNZ News podcast and want to only download the 5pm bulletins (eg episode title "RNZ News at 5pm, July 26") , so I:
1. enabled the Add to selected playlists
2. set the Auto download to 10,

In the Auto download filter I:
3. Checked the Filter episode title
4. Selected the Download episode
5. Selected Match all keywords
6. Added the keyword `5pm`

The subtext on the Auto download filter button now reads
> Download episode if match all keywords 5pm.

But all episodes still get downloaded (including 7am, 12pm and 10pm bulletins)

**Comment by gemiren** [comment]
Please turn off the option "Add to selected playlists". The downloaded episodes will always be added to the playlists. 

If you have "Add to selected playlists" enabled then all new episodes will be added to the playlists regardless whether they are downloaded or not.
