### ISSUE TITLE
Unable to add YouTube playlist

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#296]
I couldn't add any YouTube playlist by URL even though I tried to add several

**Comment by gemiren** [comment]
Can you send the YouTube playlist URL? I can give it a try. Thanks.

**Comment by oddtoddy** [comment]
I've been able to add playlists without any issue. Can you see if this works? PLNjtpXOAJhQLmUEyuWw4hW_6gX8JMJUof

**Comment by vlzuykov** [comment]
> Can you send the YouTube playlist URL? I can give it a try. Thanks.

For example:
https://youtube.com/playlist?list=PLKWMwYtiLVW1pCnF4SRS9ATY7gKMMdyOg
https://youtube.com/playlist?list=PLyXor-IbFvGSCu4Y42ggsSGYF4Gzp76u6
https://youtube.com/playlist?list=PLZrG2M8ZbpEWFzsue6Y9YYRA7tQzFJ2C-

I tried to add a lot of playlists, but none worked. But any channel is added without problems.

>Can you see if this works? PLNjtpXOAJhQLmUEyuWw4hW_6gX8JMJUof

It also fails to add.

**Comment by gemiren** [comment]
Thanks for the links. Turns out the app is looking for YouTube URL starting with www.youtub.com. If you add the missing www to the playlist URL then the app can find the podcast correct. Will fix that in the next update.
