### ISSUE TITLE
Move downloaded files - Wrong data in Notification

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#30]
After "Moving downloads" to another folder, the Pop Up Notification containing is wrong Source Folder!

**In app:** Move all files from [primary:Podcasts] to the new download directory [primary:Podcasts/Files]?

**In Notification:** Move all files from [/storage/emulated/0/Podcasts/Files/*.mp3] to [/storage/emulated/0/Podcasts/Files]

Source directory is /storage/emulated/0/Podcasts/ **not** /storage/emulated/0/Podcasts/Files/

**Comment by gemiren** [comment]
Fixed in today's beta update.
