### ISSUE TITLE
Smart download issue 

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#305]
I am subscribed to a certain podcast. Automatic downloads are disabled. Smart downloads are set to 1. The first episode of this podcast was downloaded and added to the playlist a few days ago.
The feed of this podcast has been updated, and the new episode (4th) has just been retrieved. Right after retrieving the new episode, the second episode started downloading. When this happened, I hadn't started playing the first episode of this podcast yet.
I have noticed this behavior for the second time.

**Comment by gemiren** [comment]
This is the correct behavior. If the 'Auto download' option is disabled but 'Smart download' is enabled then 'Smart download' will be triggered when new episodes are retrieved from the podcast feed.

**Comment by vlzuykov** [comment]
I thought 'Smart download' will be triggered when new episodes are retrieved from the podcast feed only if number of currently downloaded episodes are lower then 'Smart download' positive value.
It's looks like a bug to me because I have many periodically updated podcasts that have 'Smart download' set to 1, but most of the time when one or more episodes of such podcast have already been downloaded, the next episode didn't downloaded when new one was retrieved.

**Comment by gemiren** [comment]
> I thought 'Smart download' will be triggered when new episodes are retrieved from the podcast feed only if number of currently downloaded episodes are lower then 'Smart download' positive value.

No. 'Smart download' checks whether the unplayed N number of episodes after or before the last played episode are downloaded or not. The total downloaded number doesn't matter here.

> It's looks like a bug to me because I have many periodically updated podcasts that have 'Smart download' set to 1, but most of the time when one or more episodes of such podcast have already been downloaded, the next episode didn't downloaded when new one was retrieved.

When you say the next episode do you mean the next episode after currently playing or last played episode?

**Comment by vlzuykov** [comment]
> When you say the next episode do you mean the next episode after currently playing or last played episode?

What I mean is that when one or more episodes of such podcast are already downloaded, usually no episode was downloaded immediately after retrieving a new one if Automatic download is disabled and Smart download is set to 1.


> The first episode of this podcast was downloaded and added to the playlist a few days ago.
> The feed of this podcast has been updated, and the new episode (4th) has just been retrieved. Right after retrieving the new episode, the second episode started downloading.

When this happened, I never started playing that first episode (or any other episode of this podcast), but the second one started downloading when the fourth one was received.

**Comment by vlzuykov** [comment]
Another podcast's feed has just been updated, a new episode has been received, and the episode after the one that was listened to in its entirety a few days ago has begun to download. Is this the correct behavior, given that the trigger for downloading episodes from the middle of a podcast that the user has already forgotten about is the release of a new episode?

I would consider it smart if the application pre-downloads a certain number of episodes for continuous listening of several episodes of the same podcast, or when immediately after a certain episode starts playing, the next one is downloaded, thereby adding it to the listening plan (playlist).

**Comment by gemiren** [comment]
Initially 'Smart download' is triggered only after you start playing an episode. However, there's an interesting use case. Assuming you have 'Auto download' option disabled but have 'Smart download' option enabled for a podcast. You've finished all episodes of that podcast. Now, when a new episode is retrieved it won't be downloaded automatically since 'Auto download' is disabled. You have to download that new episode manually. In this use case, it would be handy if 'Smart download' can download that new episode. This is the reason why 'Smart download' is triggered during the podcast update.

In the current implementation 'Smart download' always kicks in if 'Smart download' is disabled. Maybe we should stick to the use case above strictly. Maybe 'Smart download' should kick in only if there's no download from the podcast, or no more unplayed episodes, or both? What you think?

**Comment by vlzuykov** [comment]
I think the Smart download should be tweaked. 
It shoud have only those triggering cases:
1. When a user start playing an episode, it shoud download next or previous edpisodes to match the selected number.
2. When new episodes are retrieved from the podcast's feed, but only if the number of next (or previous) episodes was lower than selected number at the moment when a user have been starting to play the last episode.

Now it has third triggering case I think should be removed: When new episodes are retrieved from the podcast's feed it will download some number of next/previous episodes to match the selected number, even if all those episodes existed then a user have been starting to play the last episode.
This case is bad for two reasons:
1. I set Smart download to 1. When l listened to some episode, the app downloaded the next episode. It's fine since I has enabled Smart download. But if don't want to listen to this next episode, I'll delete the download. I haven't listened to any other episode of this podcast, so when the new episodes will be retrieved, this manually deleted episode will be downloaded again. Now matter how many times I deleted it, this episode will be downloaded over and over again. I don't want to disable smart download feature for this podcast because when I will start playing some of the new episodes, I would like those two triggering cases, that was described above.
2. I listened to some episode in the middle of the podcast. Then I set Smart download to 1 for this podcast. And again, the next or previous episodes will be downloaded when the new ones was retrieved even if those downloaded episodes existed at the time when I played this episode.

**Comment by gemiren** [comment]
Just pushed a new beta build to the beta channel on Play Store. Now Smart download would kick in during the podcast update to download the episodes which are retrieved recently and within the number of episodes to be downloaded as if the last played episode is playing.

For example, say your last played episode is #5. After updating, a new episode #6 is retrieved, then, this episode will be downloaded. If your last played episode is #4 then the episode #6 won't be downloaded, assuming Smart download is set to 1.

**Comment by vlzuykov** [comment]
Thanks, now it works as it should!
