### ISSUE TITLE
An episode is not removed from the playlist when the downloaded file of that episode is manually deleted

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#306]
When I manually delete the downloaded file from the podcast page by pressing on horizontal three dots button and then pressing on Delete download, this episode is successfuly deleted from the default playlist.
But if I go to playlist page (and the podcast page as well), long press on the same episode, go to episode menu, press on vertical three dots button and then press on Delete download, this episode stays in the playlist with the Stream label, even after restarting the app.

**Comment by gemiren** [comment]
Will fix that in next update. Thanks.
