### ISSUE TITLE
"Podcast priority" is used in the wrong context

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#308]
![Screenshot_2023-08-15-12-13-58-021-edit_com.itunestoppodcastplayer.app.jpg](https://github.com/Podcast-Republic/PRApp/assets/2944126/34580bd0-fad1-4ee0-922c-feb85ba31bc4)

**Comment by gemiren** [comment]
Will fix that in the next update. Thanks!
