### ISSUE TITLE
Missing strings from strings.xml - Not translatable

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#31]
Two missing strings...

1. "HTML Notation"
2. "Media buttons"

[Screenshots here](https://photos.app.goo.gl/tjpHp3moRQNqbAA57)

**Comment by gemiren** [comment]
Added in the latest commit. Thanks.

**Comment by oldman63** [comment]
> Added in the latest commit. Thanks.

In 21.11.6b3

The problems still exists!
?
