### ISSUE TITLE
"Chapter [%1$s] will be skipped!" notification pops up in the center of the screen

### ISSUE THREAD

**Issue by KostanKettch** [Podcast-Republic/PRApp#310]
![image](https://github.com/Podcast-Republic/PRApp/assets/17114904/84ce0b0c-c0c4-4dee-84a7-1df8fde6ed1c)
Shouldn't it be anchored to the bottom?

**Comment by gemiren** [comment]
Nice catch! Will fix it in the next update.

**Comment by KostanKettch** [comment]
Thanks for fixing. 
Same issue on the "What's new" notification. 
![Screenshot_20230902_090042_com.itunestoppodcastplayer.app.jpg](https://github.com/Podcast-Republic/PRApp/assets/17114904/76f1807a-8bd2-4b21-a2c4-0b6346408cf3)
