### ISSUE TITLE
"What's new" notification pops up in the center of the screen

### ISSUE THREAD

**Issue by KostanKettch** [Podcast-Republic/PRApp#336]
Same problem as [this one:]( https://github.com/Podcast-Republic/PRApp/issues/310)
![image](https://github.com/Podcast-Republic/PRApp/assets/17114904/870dd435-5322-45cb-95f6-9b4aa07b6aae)

**Comment by gemiren** [comment]
It's by design. If the Now playing screen is displayed then the message will appear above the timeline bar in order to not cover the other controls. Thanks.
