### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#35]
The another missing string. See picture:

<details>
<summary>Image</summary>

![untranslatable_string](https://user-images.githubusercontent.com/37414585/140616383-35ad2e21-c1eb-48ee-b965-cf7d9438581c.png)

</details>

**Comment by gemiren** [comment]
Added. Thanks very much!

**Comment by oldman63** [comment]
Another two untranslated 
![Screenshot_20211107-120907_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140646250-497f2aac-6202-499f-ac92-ed70b770a9e7.jpg)
string...

![Screenshot_20211107-120957_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140646190-4f01783a-6d34-4c1f-acad-0ce09fc95f81.jpg)

**Comment by gemiren** [comment]
The one in the first screenshot actually is the summary of the RSS feed.

The second one should use new_article_notification string. Will update it.

Thanks.

**Comment by oldman63** [comment]
Thanks.

**Comment by gemiren** [comment]
Updated in today's beta update.
