### ISSUE TITLE
I cannot find widgets settings

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#36]
Where is widgets settings, it missing in app.

<details>
<summary>Missing widgets settings</summary>

![widgets_missing](https://user-images.githubusercontent.com/37414585/140616606-0a98949c-4688-44b4-a427-62eb811ddf5b.png)

</details>

**Comment by gemiren** [comment]
If you don't have a widget added to your home screen then the widget options won't show up.

**Comment by oldman63** [comment]
> If you don't have a widget added to your home screen then the widget options won't show up.

Please add this info to FAQ!
:-)
