### ISSUE TITLE
Wrong time format in translations

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#39]
21.11.6b3

Time format is english in this string:

string name="you_ve_listened_b_d_s_b"

[Screenshot and mark](https://photos.app.goo.gl/QqJVxRNGGiFWxhG7A)

**Comment by gemiren** [comment]
Will fix it in next update. Thanks.

**Comment by oldman63** [comment]
Next:

![Screenshot_20211107-143411_Podcast Republic-3](https://user-images.githubusercontent.com/3171626/140647512-a08b7eb8-4c7c-43d4-a4e4-8eae1fb938ac.jpg)

**Comment by gemiren** [comment]
Here the symbol **s** is used as the second. It's not translated because even the abbreviation (sec in English) is too long to fit the UI.

**Comment by oldman63** [comment]
> Here the symbol **s** is used as the second. It's not translated because even the abbreviation (sec in English) is too long to fit the UI.

Thx. I know...

The "s/second" is "mp/másodperc" in hungarian language.

**Comment by gemiren** [comment]
IMHO, "mp" would be too long for this UI design. What you think?

**Comment by oldman63** [comment]
Ok, "s" is good for me.

**Comment by oldman63** [comment]
Next.

This also can't be translated because the abbreviations here are too long to fit the user interface?
:-)

![Screenshot_20211109-143936_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140937444-9c816ae4-29aa-4a88-bf46-b61519eee81e.jpg)

**Comment by gemiren** [comment]
If there's an equivalent of the shortest format then I'd be more than happy to adopt. Otherwise, I'd say let's keep using H, M and S.

**Comment by oldman63** [comment]
> If there's an equivalent of the shortest format then I'd be more than happy to adopt. Otherwise, I'd say let's keep using H, M and S.

H -> Ó
M -> P
S -> MP

**Comment by gemiren** [comment]
Will do.

**Comment by oldman63** [comment]
21.11.10R2

Excellent update! Thank you the fix.
