### ISSUE TITLE
[Bug] Notifications remain in the notifications panel

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#403]
I think that since version 24.1.8b, autoremoving the notification from the notification panel does not work. After playback ends, the notification remains in the notification panel.

Can you have a look at it, please?

**Comment by gemiren** [comment]
Are you able to swipe to dismiss the notification?

**Comment by kubalav** [comment]
Yes, I can.

**Comment by kubalav** [comment]
@gemiren No new info?

**Comment by gemiren** [comment]
If the notification can be dismissed then I'm not worried about that.

**Comment by kubalav** [comment]
I was used to it always closing on its own. If you can't fix it, never mind.
