### ISSUE TITLE
bug: 500 server error on login

### ISSUE THREAD

**Issue by megahirt** [Podcast-Republic/PRApp#407]
Hi,

I'm a long time podcast republic user on Android.  I recently cleared my app cache and so needed to sign in in order to sync my podcasts.  The sign in failed on Android but it wasn't clear why (just says the username/password doesn't match).  When I sign in in a browser I can see a 500 server error, which is likely also happening in the Android app.

Google oauth login appears fine, but I have a username/password and I cannot login.

<img width="1237" alt="image" src="https://github.com/Podcast-Republic/PRApp/assets/3444521/2d610bfc-e205-4329-8fdc-e57f9ba6a3d6">

My username is chris@hirtfamily.net / megahirt

**Comment by gemiren** [comment]
Thanks very much for the bug report. The syncing server is overloaded constantly. Please give it a try later.

**Comment by megahirt** [comment]
OK, I'll give it another try and see if it works later.  Will report back.

Chris
