### ISSUE TITLE
FR (Android Auto): Option to replace Prev / Next with Fast Forward / Rewind in task bar and split screen

### ISSUE THREAD

**Issue by ToastyKen** [Podcast-Republic/PRApp#411]
For Android Auto, there are options to enable Fast Forward and Fast Rewind buttons, but they only appear in full screen mode. I'm the task bar and in split screen mode, only the Previous / Next track buttons are available.

Requesting an option to display Fast Forward / Rewind buttons in place of Previous / Next Track buttons in these cases, as I use them far more than skipping to the next track.

**Comment by gemiren** [comment]
Starting with Android 13, if my memory is correct, Google has hardcoded the Previous and Next controls into the media notification. The only way to remove those two controls is to set up the app not to support the Previous and Next actions at all. That's not what this app wants, unfortunately.

The workaround is to remap those two controls to Fast forward or Fast rewind action through the app Settings > Media player > Bluetooth/headset key mapping.

Thanks.

**Comment by ToastyKen** [comment]
Fantastic! Thanks. I'll try that!

**Comment by ToastyKen** [comment]
Closing as it sounds like this isn't possible
