### ISSUE TITLE
Icon and text collision

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#412]
The Sign out text is overlapped by an edit icon. This is Slovak translation. I can edit translation unless there is no other option. In other languages is the same problem. The username can be limited or pencil icon moved to another location.

P.S.: I noticed if the theme is set to dark, the language selection page is light (intention or bug?).

![obrázok_2024-03-31_111936476](https://github.com/Podcast-Republic/PRApp/assets/37414585/a9898cf1-f7b3-4da5-9fd6-cff21cfee9ee)

**Comment by gemiren** [comment]
Will fix the overlapping issue. Regarding the language selection page theme, I assume you are on Android 14, please note that the language selection page is a page provided by Android system, it uses the Android system's theme, not the app theme.

**Comment by kubalav** [comment]
Yes, I'm on A14 and you're right.
