### ISSUE TITLE
The speed menu does not fully pull up in landscape mode

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#428]
I'm using Android 14. When I press the speed button in landscape mode, the menu doesn't display the whole menu, but only a small portion.

**Comment by gemiren** [comment]
You can scroll up to view the rest of the popup screen. Have you tried that?

**Comment by kubalav** [comment]
I can slide the menu out to be seen. In previous versions it slid out fine. I consider it a bug.

**Comment by gemiren** [comment]
Fair enough. Will look into the issue. Thanks!

**Comment by kubalav** [comment]
Fixed!
