### ISSUE TITLE
Translating mismatch?

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#43]
At the bottom of "Settings / Widgets":

The correct Hungarian word is "Összes" not "Minden"!
"Minden" is not found in strings.xml
???

"Összes" found this: `<string name="all">Összes</string>`

English and Hungarian language screenshots:

![Screenshot_20211107-143306_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140647574-97a7f11c-d9ae-4e3a-9af2-8e27488b4e89.jpg)

![Screenshot_20211107-143327_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140647580-2ccd0b4d-e9d0-4630-bbc8-611c817a1a19.jpg)

**Comment by gemiren** [comment]
It should display the selected RSS feed tags. I'm not sure why it displays **Minden**. Does it still display **Minden** after restarting the app?

**Comment by oldman63** [comment]
Yes, after reboot device. The 'Minden" is displays.
:-)

???

**Comment by gemiren** [comment]
That's weird. I'm not able to reproduce it.

**Comment by oldman63** [comment]
Then it stays that way, I'll check it out in the next version.

**Comment by oldman63** [comment]
After uncheck and check again the "Összes/All" item -> solved the problem!
:-)
