### ISSUE TITLE
"Reset articles" instead of "Reset episodes"

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#434]
![Screenshot_2024-06-04-15-16-48-984_com.itunestoppodcastplayer.app-edit.jpg](https://github.com/Podcast-Republic/PRApp/assets/2944126/fa2d2b99-fbb2-4d05-b22e-38e6413fd2f5)

**Comment by gemiren** [comment]
Nice catch. Will get it fixed ASAP. Thanks!
