### ISSUE TITLE
Behaviour of "Compact view" and "Show descriptions" in "Display options"

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#437]
Hi,
First of all thanks for your work, appreciate it a lot. Keep up the good work!
Today I found a confusing behaviour between "Compact view" and "Show descriptions" in "Display options".

Steps to reproduce (version 24.6.17R):
1. Open an episode list of a podcast
2. Open "Display options"
3. Make sure in "Show description" is on in "Display options" 
4. Active "Compact view" 
5. (do not close the menu)
6. Deactivate "Show description" (deactivates "Compact view", see preview in background?)
7. Deactivate "Compact view" (activates "Compact view")
8. Now the complete dialog is messed up

Also: When "Compact view" is activated "Show description" is not shown when go back to another screen and return to it.

To avoid this you should imho consider to disable "Show description" and lock it when "Compact view" is being activated.

So long, fredsleeve

**Comment by gemiren** [comment]
Nice catch! Thanks very much for the detailed bug report. I'm able to reproduce this bug by following your steps. Will get it fixed ASAP.

**Comment by fredsleeve** [comment]
Thanks, that was fast and is fixed with version 24.6.17R.
But please check if issue #446 might be related to this fix.
