### ISSUE TITLE
German translation XML not up to date?

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#438]
Wanted to fork the project to fix some major translation flaws in the German. Found out that the current XML seems not be the latest from the app? E.g. "Mono audio" in the German XML and in the app it's "Mono-Audio" (which is correct).

One translation error is "Anheuern" (sign up), which means in German to pay/recruit a sailor (see https://de.wikipedia.org/w/index.php?title=Anheuern&redirect=yes) and reads super odd for a native German.
"Sign up" means "Registrieren" in German (compare https://layla-patisserie.com/en/web/signup and https://layla-patisserie.com/web/signup).

**Comment by gemiren** [comment]
Just update the translation file to the latest version used in the app. Thanks very much for helping with the translation. Much appreciated!
