### ISSUE TITLE
Bug report is broken?

### ISSUE THREAD

**Issue by splisp** [Podcast-Republic/PRApp#447]
From the app, selecting Settings | About | Report a bug,, an offer to share the log zip using all possible share intents is presented but there's no specific address to share it to.

**Comment by gemiren** [comment]
Just select any email app when sharing the log zip. The email address will be filled automatically. Thanks.

**Comment by splisp** [comment]
> Just select your email app when sharing the log zip. The email address will be filled automatically. Thanks.

Ah, ok. I wasn't expecting it 😉 thanks!
