### ISSUE TITLE
Please add long description field to "Play bar" section

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#45]
Please add long description field to "Play bar" section.

For this string:
`<string name="show_play_next_episode_station_button">Show Play next episode/station button</string>`

The Hungarian translation is too long, it cannot be further abbreviated in an understandable way.

![Screenshot_20211107-151635_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140648999-8cdd2537-4897-4241-8537-5c0f5ac7681a.jpg)
![Screenshot_20211107-151646_Podcast Republic](https://user-images.githubusercontent.com/3171626/140649002-5590b7b3-a8f7-40c8-9513-e03719294335.jpg)
![Screenshot_20211107-151707_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140649003-cd1381dc-b4b9-453e-9590-8b9009be349a.jpg)

**Comment by gemiren** [comment]
Nice catch! Will do.

**Comment by gemiren** [comment]
Added in today's beta update.

**Comment by oldman63** [comment]
21.11.10R2

Excellent update! Thank you the fix.
