### ISSUE TITLE
"Preview note" option in episode filter is not displayed correctly

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#450]
Version: 24.7.11b

Attention, this is a tricky one.
Steps to reproduce:
1. Add a note at least to one podcast episode
2. Create a custom episode filter in "Episodes" without any filter
3. In your recently created new episode filter make sure that "Compact view" and "Show description" are disabled in "Display options"
4. Go to "Edit episode filter"
5. Enable switch "Notes"
6. Now in the episode filter your episode with the note will appear
7. Go back to "Edit episode filter" and enable "Preview notes"
8. Enable "Show description" in "Display option" 
9. Result: The preview of the note is not shown instead the episode description
10. Edit episode filter again and disable "Preview notes" when "Show description" is enabled will show the note. But now the state of the switch does not represent the result of the switch. 

It looks like this only happens in combination with "Preview notes" and "Notes"  when both are used separately.
Btw: The description of "Preview notes" should note that this option will be shown the episode description instead. I was wondering what this option does and it took a while to find it (and then found this bug).

**Comment by gemiren** [comment]
Thanks very much for the detailed bug report. I was able to reproduce this bug by following your steps. The bug has been fixed now. The fix will be included in the next (beta) update.

Will update the text as well.

Thanks!

**Comment by fredsleeve** [comment]
Update arrived, looks good.
Was there a change in the translation string in the XML for the "Preview notes description thing"? I'm asking because I would like to pull a new version for German within the next days (found minor typos).

**Comment by gemiren** [comment]
Thanks very much for confirming the fix. Yes, I've updated the text. Please use the new version for translation. Thanks!
