### ISSUE TITLE
Add to "Default playlist" feature does not work

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#454]
Found in latest beta, but I noticed the issue also in the stable releases before.

1. Make sure unplayed play listist empty for better overview
2. Create a new custom playlist and set it as your default (can be checked/set also in settings)
3. Go to a podcast feed and add one episode via "+" from the episode list.
4. Episode is now in unplayed instead in your default playlits

Addtional note: The "right swipe action" option in episodes settings for this does also not work. Please also note the typo "Add to default playlists", this intends that there is more than one default. But as I can see there can be only one default (which makes sense).

**Comment by gemiren** [comment]
Nice observation. There are types of default playlist(s) in the app:
- App wise default playlist. You can select one playlist as the app's default playlist.
- Podcast 's default playlists. You can select one or multiple playlists as a podcast's default playlists through podcast settings.

When you subscribe to a podcast, the app's default playlist is added to the podcast's default playlists. If later you changed the app's default playlist, the podcast's default playlists won't be updated to the new app's default playlist.

The swipe action adds the episode to the podcast's default playlists, not the app's default playlist.

**Comment by fredsleeve** [comment]
Ok thanks. Now I understand how this works. :-)

Additional question regarding playlist: There's a setting in "Playlists" which is called "Auto load last played episode into 'Now playing'". I do not find this playlist "Now playing", so what's up with this?

**Comment by gemiren** [comment]
'Now playing' is not a playlist, it's the screen showing the currently playing item. For example, the mini play bar and the expanded full screen 'Now playing' screen.

**Comment by fredsleeve** [comment]
Sorry, don't get it. With "Now playing" you don't mean Android system item?
I do not see any difference in the app when using or not using this option.

But: When I enable this option and apply for all podcasts when askes, all of the episodes from the next played podcasts episode of the podcast will appended to "up next".

**Comment by gemiren** [comment]
![nowplaying.png](https://github.com/user-attachments/assets/4abe0f41-33a2-47d6-8cc5-5c51407295a7)

Attached is the 'Now playing' screen in the app.

**Comment by fredsleeve** [comment]
Yes, I know that this is related to Settings > Playlists >Update next automatically, but it is disabled in my case. Please check if it's reproducable.

**Comment by gemiren** [comment]
Will look into that. Thanks!

**Comment by fredsleeve** [comment]
> ![nowplaying.png](https://private-user-images.githubusercontent.com/7810771/348711121-4abe0f41-33a2-47d6-8cc5-5c51407295a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjI3NDEsIm5iZiI6MTcyMTA2MjQ0MSwicGF0aCI6Ii83ODEwNzcxLzM0ODcxMTEyMS00YWJlMGY0MS0zM2EyLTQ3ZDYtOGNjNS01YzUxNDA3Mjk1YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMTY1NDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU2MTUxMzRhMDlhMjE0MWExNDJmZjFmODJlYWRjYzBjZDJhOGM5NzI4ODkwOTFhZWQ0YWMyMWJkNTVkNTg0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ci3bBbkI_aAnBRF__ntTzD90DybktsRh1XReAMkA0kk)
> 
> Attached is the 'Now playing' screen in the app.

Yes I already thought that, but when should this appear? After leaving the podcast, restarting the app, using playlist... still don't understand. I know this screen but and how does this interact with this option. Do not see any difference in the behaviour if the option is disabled or enabled.

**Comment by gemiren** [comment]
> Yes I already thought that, but when should this appear? After leaving the podcast, restarting the app, using playlist... still don't understand. I know this screen but and how does this interact with this option. Do not see any difference in the behaviour if the option is disabled or enabled.

The 'Now playing' screen always displays what's currently playing or last played. When you press the Play button the app will start playing the item displayed in the 'Now playing' screen.

Say you have two playlists A and B. The last played episode in each playlist is A2 and B3 respectively. With the option 'Auto load last played episode' enabled, if you go to the playlist A, you'll see episode A2 shows up in the 'Now playing' screen. Switch to the playlist B, you'll see the episode B3 shows up in the 'Now playing' screen. If that option is disabled then, - the 'Now playing' screen won't be updated when you switch to another playlist.

This option is handy as it saves you the time to find which episode you were playing last time in the playlist.

**Comment by fredsleeve** [comment]
Thanks, now I understand this option. Reading description it was (for me) not clear what it does and I also didn't recognize what it really does when this is enabled. Maybe the desciption needs to be more precise or it's PEBCAK. ;-)
