### ISSUE TITLE
"Play next epsiode" button missing, equalizer instead?

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#457]
Version: 24.7.16b

"Play next episode" button is not displayed instead I see the equalizer now. I played around with playlist features (quite confusing for me) and since them I can no longer see the "next episode" button. Any ideas how to get it back?

![Screenshot_20240720-143229](https://github.com/user-attachments/assets/2a36479b-b950-4808-92ae-90436f29d0c8)

**Comment by gemiren** [comment]
In the app Settings > User Interface > Play bar > Play next episode/station, please make sure that option is enabled.

**Comment by fredsleeve** [comment]
Thanks, got it.
