### ISSUE TITLE
Wrong label in "Smart rewind" option

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#459]
Version: 24.7.16b

1. Open Settings -> Media player -> Smart rewind and enable it
2. Both options are labeled with "Minimum rewind time"
3. If you change the bottom option, the label changes to "Maximum rewind time" (as it should when opening the option window)

**Comment by gemiren** [comment]
Nice catch. Will fix it in the next update. Thanks!

**Comment by fredsleeve** [comment]
Fixed in latest Beta. I'm closing this one.
