### ISSUE TITLE
Marked favorites not filterable when podcast not subscribed

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#460]
Version: 24.7.24b

1. Search for a random podcast and mark one episode as favorite (do not subscribe the podcast)
2. In episodes the favorite filter is not showing the marked episode.
3. If this is supposed to work like this, please make sure you cannot mark an episode as favorite when podcast is not subscribed.

**Comment by gemiren** [comment]
Currently, this is by design not showing unsubscribed podcasts in the filtered list. Thanks.

**Comment by fredsleeve** [comment]
Thanks for clarifying. Maybe you can improve this someday by disabling the favorite feature in non-subscribed podcast, because I was quite confused while didn't find them. :-)

**Comment by gemiren** [comment]
Sure, will consider that for future updates. Thanks!
