### ISSUE TITLE
Checkbox in episode search not working/visible

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#467]
See uploaded video: https://c.gmx.net/@334288198261801446/MJ3ANBlFQH6HYvEuCBTXZA
If you select "Only show" date search in podcasts, it is enabled in episodes too but it's not visible.

**Comment by gemiren** [comment]
Nice catch. Will fix it in the next update. Thanks!

**Comment by fredsleeve** [comment]
Closing, fixed in latest beta.
