### ISSUE TITLE
Wrong playback buttons when episode is paused and entering settings

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#470]
Version: latest beta 24.8.2b

1. Play an episode and pause it
2. Move it down so it's in the lower menu bar ("tray")
3. Note: The buttons "x" and  ">" are shown (when playing "x" is replaced with ">|" for next episode)
4. Go to profile > settings and go back
5. The tray now shows all three buttons: "x", ">|" and ">"
6. I don't think this supposed to show like that

**Comment by gemiren** [comment]
Nice catch. I'm able to reproduce this bug by following your steps. Will get it fixed ASAP. Thanks.

**Comment by fredsleeve** [comment]
Fixed in latest, beta
