### ISSUE TITLE
"Up next" list shows playing animation multiple episodes 

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#472]
Latest beta 23.8.4b

1. Add multiple episodes to "Up next"
2. Open "Up next" so you have all episodes in a list
3. Start playing one episode
4. Tap another episode in the list -> the playing shows for the new played episode but still remains for the old on
5. This also occurs  when using the next/prev buttons
6. This does not occurs if you tap the episodes directly in the profile tab without opening "Up next" list

![Screenshot_20240805-190530](https://github.com/user-attachments/assets/3756d113-b6b5-4c09-a069-3def22cc5832)

**Comment by gemiren** [comment]
Thanks very much for the bug report. Will get it fixed ASAP.

**Comment by fredsleeve** [comment]
Fixed with latest beta
