### ISSUE TITLE
Auto update of "Up next" replaces manual added episodes when they are added with "play next"

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#474]
Latest beta 23.8.4b

See screen recording:
https://c.gmx.net/@334288198261801446/372bMPzGQaKP7UceX_HTxA

This happens when "Update Up next automatically" is enabled and when episodes are being added with "play next". It is not reproducable when the episodes are added with "append to Up next". So there must be an issue when episodes are being added between the episodes of "Up next".

**Comment by gemiren** [comment]
Nice catch. I was able to reproduce this bug and got it fixed. The fix will be in the next update. Thanks!

**Comment by fredsleeve** [comment]
Confirmed, fixed in newest beta.
