### ISSUE TITLE
Search list "Add/subscription symbol" doesn't change

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#483]
Version 21.8.9R

1. Go to "Subscription"
2. Go to "Discover"
3. Search for a podcast/station
4. In the list of the search results, click on the "+" symbol on the right
5. The item will be now added to your subscrpitions but the symbol doesn't change (also no message appears)
6. (if you use the long tap action and the subscripe action the symbol changes)

**Comment by gemiren** [comment]
Will fix that. Thanks.

**Comment by fredsleeve** [comment]
Got the latest beta. Symbol changes now to the green check icon and subscribes, but you if you click the "+" again and it did not unsubscribe the podcast.

**Comment by gemiren** [comment]
Will fix it in the next update. Thanks!

**Comment by fredsleeve** [comment]
Closing, fixed with latest beta
