### ISSUE TITLE
Missing unicode character set in HTML export

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#488]
24.8.22b

1. Create a playlist from a German podcast "Stay Forever" and add e.g. episode "Planetfall (SF 144)"
2. Now export this playlist as HTML
3. Open the created HTML file with a browser
4. You'll see that German special characters like ü,ö,ä and so on will not be displayed correctly.

For testing purpose I added `<meta charset="utf-8">` after `<html>`: With this, the characters are correct displayed.

**Comment by gemiren** [comment]
Nice catch. Will fix it in the next update. Thanks!

**Comment by fredsleeve** [comment]
Closing, fixed with 24.8.30b
