### ISSUE TITLE
Podcast search doesn't work after search box looses focus

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#489]
Version 24.8.22b

Steps to reproduce:

1. Open a Podcast feed
2. Enter search by tapping the magnifier symbol
3. Enter search a term -> results should appear
4. Leave the focus of search box by scrolling down in the result list
5. Scroll up and enter search box again
6. Enter a new search term -> search results do not change, also not by tapping the magnifier symbol
7. You have to close the search box to get the search working again

**Comment by gemiren** [comment]
Fixed in today's beta update. Thanks!
