### ISSUE TITLE
Wrong translations, but not found the strings.xml

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#49]
The "órával" and "hours ago" is not found in strings.xml

Marked in screenshots below

![Screenshot_20211109-075035_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140880885-0bdf1e93-f623-4280-b925-7be8c5a9fd68.jpg)
![Screenshot_20211109-075052_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/140880887-21c9849e-01cc-42b0-aa78-0900cbba8040.jpg)

**Comment by gemiren** [comment]
This relative time text is provided by Android system and localized according the selected language/locale. App doesn't need to translate them.

**Comment by oldman63** [comment]
Thx.
It is unfortunate because it is not grammatically correct.

not correct: órával
correct: órája (or "órával ezelőtt")

**Comment by gemiren** [comment]
You are right. The relative time display actually gets cut off due to the width limit. Will fix that.

**Comment by oldman63** [comment]
Welcome this news! :-)

New screenshots below...

not correct: órával -> órával ezelőtt (órája)
not correct: perccel -> perccel ezelőtt (perce)

![Screenshot_20211110-074504_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/141064152-67642d20-dbc5-4d1b-bea2-4567eccadfef.jpg)

**Comment by gemiren** [comment]
That's the same issue. Will be fixed in next beta update. Thanks.

**Comment by oldman63** [comment]
21.11.10R2

Excellent update! Thank you fox fix.
