### ISSUE TITLE
Auto download and episode filter: Missing information when both options are active

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#498]
Version 24.8.30b

1. Open settings of a podcast
2. Create an episode filter with both options enabled (filter episode title + episode duration)
3. In the settings overview only "Filter episode title" will be displayed, "Filter episode duration" is missing.
4. Same for "Auto download filter". Note that when these options are enabled a precise summary appears in the overiew.

Guess this should be fixed for UX, e.g. by concatenate both options summaries in the overview. Note the missing periods "episode filter".

**Comment by gemiren** [comment]
Will fix that. Thanks!

**Comment by fredsleeve** [comment]
Fix in 24.9.5b
