### ISSUE TITLE
Multiple issues with adding episodes to playlist

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#500]
Version 24.9.1R

I have encountered multiple issues when trying to add episodes to playlist:

1. Screen recording 1: https://c.gmx.net/@334288198261801446/ZdCKtOWsTOe_PlXdJj9EOQ
- Episode won't be added to defined default playlist for episodes found via podcast discovery.
- Epsiode from subscribed podcast will not be added to default playlist, message "No playlist selected" appears.

2. Screen recording 2: https://c.gmx.net/@334288198261801446/6WYNp7cLS-qIJIqEfoERIA
- Contrary to the issue from 1st recording, I can add episodes to playlist via episode search.
- Cannot add episodes for a subscribed podcast, when it was found via episode search. The message it has been added to playlist appears, but it isn't. It works when using the subscribed podcast feed.

**Comment by gemiren** [comment]
Thanks very much for the bug report. I tried a few times but couldn't reproduce either of the two issues. Are you able to reproduce them?

**Comment by fredsleeve** [comment]
Yes, it's reproducable and persistent.
I found out that I had more playlists on my 2nd device (4).
On the 1st device from which this bug report was taken, I had only 2 which were also on the 2nd device. The other two from my 2nd where missing on my 1st device.
So I deleted now playlist and created a new default playlist.

Now the "default playlist" option isn't working anymore:
1st bug: Every time the message "No playlist selected" (it only work when using the "+" in episode list and not from menu)
2nd bug: Still exists.

**Comment by fredsleeve** [comment]
Update:
I am able to reproduce the 1st bug on a 3rd device. PRApp wasn't installed before, no account login, see screen recording:
https://c.gmx.net/@334288198261801446/dYq-MmGfQRikgsr1bjh66A

Regarding the 2nd bug: I have noticed that no pop up appears when pressing the "+" icon, see screen recording of my 3rd device (compare video to bug 2):
https://c.gmx.net/@334288198261801446/lDilAc1rR1-r8ifeoD6guA

**Comment by fredsleeve** [comment]
Update 2:
I think a nailed down the problem:
1. Uninstall -> Install
2. Open a first time ->set other default playlist then "Unplayed", e.g. "Audio"
3. Add an episode to default playlist -> it appears in "Audio" as estimated
4. Change default playlist to "Unplayed"
5. Repeat step 3 and it still appears in "Audio" instead of "Unplayed"
6. Resetting the app via settings doesn't fix it, only a reinstall!

**Comment by fredsleeve** [comment]
Have you fixed this already? If so, the issue still remains in the latest beta.

**Comment by gemiren** [comment]
> Have you fixed this already? If so, the issue still remains in the latest beta.

Please go to the app Settings > Backup & restore to create a backup of the app data and then send the backup file to tech@podcastrepublic.net. I'll see if I can reproduce this issue with your app data. Thanks.

**Comment by fredsleeve** [comment]
Updated to beta 24.10.1b. Looks good now, but the message regarding not set default playlist in podcast setting appears only once for each podcast until the app restarts. Imo this should appear everytime (if possible).

Regarding default playlist one issue remains: The default playlist value from settings will not be applied to new subscriptions for podcasts, it seems the app uses the first playlist entry and not from the settings.

**Comment by gemiren** [comment]
> Updated to beta 24.10.1b. Looks good now, but the message regarding not set default playlist in podcast setting appears only once for each podcast until the app restarts. Imo this should appear everytime (if possible).
> 
> Regarding default playlist one issue remains: The default playlist value from settings will not be applied to new subscriptions for podcasts, it seems the app uses the first playlist entry and not from the settings.

Both issues are now fixed in today's beta update. Thanks.

**Comment by fredsleeve** [comment]
Closing, fixed.
