### ISSUE TITLE
App reset points to wrong default playlist 

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#502]
Version 24.9.1R

By default these 3 playlists exists: Unplayed, Audio, Video

1. Delete playlist "Unplayed"
2. Go to Settings -> Advanced > Reset
3. Open Settings -> Playlists
4. Take a look at "Default playlist": It's "Unplayed" which we have deleted before.

App reset should consider to restore at least one default playlist or all. Or it shouldn't change the default playlist.

**Comment by gemiren** [comment]
Nice catch. We shouldn't change the default playlist in this case. Will fix that asap.

**Comment by fredsleeve** [comment]
Fixed with 24.9.4b
