### ISSUE TITLE
Wrong windows title in "Car mode" 

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#505]
Version 24.9.5b

1. Play an episode
2. Go to Car mode
3. Open Overflow menu (3 vertical dots)
4. The window title of Overflow menu is "Radio stations" instead of "Car mode"

**Comment by gemiren** [comment]
Nice catch! Will fix that in the next update. Thanks!

**Comment by fredsleeve** [comment]
Closing, fixed with 24.9.9b
