### ISSUE TITLE
Wrong time format

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#51]
Please fix this

![Screenshot_20211110-074511_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/141096906-90405eb9-7c73-46e1-8689-6bcf1a30b763.jpg)
![Screenshot_20211110-074526_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/141096911-c132149e-e2ab-4c49-890a-e190ea3f898e.jpg)

**Comment by gemiren** [comment]
This played time is also localized by Android system. I'm wondering whether that's a refreshing issue? On my phone, it get updated properly after switching language locale.

**Comment by oldman63** [comment]
The time format is changed, but is incorrect.

Maybe an Android bug?
(My device is SM-G975F Samsung S10+ with Android 11)

The correct time format would be: **8 h 49 p**

**Hungarian locale:**

![Screenshot_20211113-071438_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/141608367-1d3c25de-57e4-42af-8d29-685eb62214d8.jpg)

**English locale:**

![Screenshot_20211113-071454_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/141608379-c0c54d81-165b-497a-b01d-2b762865e668.jpg)

**Comment by gemiren** [comment]
Did it get updated after restarting the app?

**Comment by gemiren** [comment]
Looks that's because the app is requesting short format. I don't know why but the short format isn't updated with the locale. Will look into it.
