### ISSUE TITLE
Chapter artwork not showing in "Now Playing" (but in "mini player")

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#511]
Version: 24.9.18b

Since a couple of (beta) versions I have observed that the chapter artworks are not loading properly and it seems that this feature works less well than before.

See screen recording: https://c.gmx.net/@334288198261801446/_QG9w4dYTAWfWuVUpykyMw
Chapter artwork does not appear in "Now playing" but in the mini player and notification.
You can test it with the German podcasts "Lage der Nation" or "Stay Forever".

**Comment by gemiren** [comment]
Thanks very much for the detailed bug report. This bug has been fixed in today's beta update. Please update your app to the latest beta version. Please let me know if the bug is still there. Thanks!

**Comment by fredsleeve** [comment]
Thanks, it's fixed. But now there's a flickering image when pausing the episode or reduce the window to the mini player, see screen recording:
https://c.gmx.net/@334288198261801446/q5vHobvVQdqGsMQwqVAyHw

Also I still having issue for episodes are not loading chapter artwork at all. This might also be related to #469.  Unfortunately I haven't found a pattern yet. Do you have any English podcast with chapter artwork which I can test?

**Comment by gemiren** [comment]
Thanks for confirming the fix. Will look into the flickering issue and fix it asap. 

The 'No agenda' podcast from Adam Curry & John C. Dvorak has chapter images in it. I mainly use this podcast for chapter related testing.

**Comment by fredsleeve** [comment]
Did some test with the mentioned 'No agenda' podcast. The result is interesting: With this podcast I have no problems with chapter images loading. With my other podcast the images are loading sometimes and sometimes not. Also episodes were image loading worked before doesn't work later.

**Comment by gemiren** [comment]
Thanks for doing the testing. The different behaviors are due to whether the image is embedded inside the podcast file or not.

The 'No agenda' podcast links an online image as the chapter image, while your podcasts embed the images into the podcast files.

The app saves the chapter image links but not the embedded images. That's why the linked online image gets loaded correctly all the time but it fails to load the embedded images in certain times.

This bug has been fixed in today's beta update. Please update your app to the latest beta version to get the fix.

Also fixed the flickering issue in the latest beta version.

Thanks!

**Comment by fredsleeve** [comment]
Thanks for detailed explanation.

I've found out that downloading an episode seems to fix this issue for "my" podcasts. In previous versions this wasn't the case when I remember correctly.

But now "Zoom image" does not work properly for downloaded episodes with chapter images: Instead of the chapter images the episode image will be shown and saving . Saving chapter image seems also not possible. But all this doesn't affect episodes from the "No agenda" podcast.

In my opinion you should also consider to show a warning message if embedded chapter images are found instead of linked images to avoid questions/reports from users.

**Comment by gemiren** [comment]
Like the chapter images can be embedded inside the podcast file or linked to online images, chapters themselves can also be embedded inside the podcast file, or provided outside of the podcast file.

If the chapters are embedded inside the podcast file then it requires scanning the whole podcast file to extract the chapters. That's not possible if you stream the podcast online. And you are right that the app at one point did attempt to scan the whole podcast file even when it's streaming. That resulted in the excessive mobile data usage if you don't have Wi-Fi connected. Thus, that's removed in the recent versions.

The 'No agenda' podcast doesn't embed the chapters inside the podcast file. Instead, it provides the chapters through the podcast RSS feed. That means no need to scan the podcast file at all. It works for both streaming and playing download.

The 'zoom image' and 'save image' operations should work on both the embedded chapter images and the online chapter images. Will look into this issue and fix it asap.

Even though the internal implementation is slightly different for the online chapter images and the embedded chapter images, they should be displayed the same to users.

**Comment by gemiren** [comment]
The zoom image bug has been fixed in today's beta update. Thanks.

**Comment by fredsleeve** [comment]
Fix confirmed, but please take a look at #517, which could be related to this fix.

**Comment by fredsleeve** [comment]
Closing, fixed.
