### ISSUE TITLE
Different looking pause icons while episode is playing

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#512]
Version: 24.9.18b

See attached screenshot.
If you play an episode you'll see two verticle lines as pause icon. In the lists the icon is instead a stop symbol. But both actions on these buttons are doing the same (pause playing).

![Screenshot_20240921-101008](https://github.com/user-attachments/assets/439f26de-e2da-4d76-8d8a-04d6713675af)

**Comment by gemiren** [comment]
Nice catch. Will fix that. Thanks!

**Comment by fredsleeve** [comment]
Fixed in 24.9.23b
