### ISSUE TITLE
Description of Reddit and Website seems to be wrong

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#514]
Version: 24.9.18b

Open "About" in settings:
- "Reddit" shows description "View what's new in this version" but opens Reddit
- Website entry shows "r/Podcast_Republic_App" which points to Reddit but open "podcastrepublic.net"

**Comment by gemiren** [comment]
Will fix that. Thanks!

**Comment by fredsleeve** [comment]
Fixed in 24.9.23b
