### ISSUE TITLE
Colored line from last played podcast remains

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#517]
Version 24.9.26R

1. Play a podcast episode and minimize to mini player
2. Close the the episode in mini player
3. The color from the podcast episode image will remain as single line above in the bottom navigation bar
4. (if you rotate your screen to landscape and back to potrait the colored will disappear, but will still be visible in landscape)

Default from scheme:
![Screenshot_20240927-155638](https://github.com/user-attachments/assets/9cb8ed46-057d-4343-847c-9f72df460e35)

While playing:
![Screenshot_20240927-113447](https://github.com/user-attachments/assets/318a17d1-88f1-4f69-ab59-c14b4b23f852)

After closing:
![Screenshot_20240927-113501](https://github.com/user-attachments/assets/90aa9fdf-1c10-4dff-a944-64289e21fffa)

While playing:
![Screenshot_20240927-113527](https://github.com/user-attachments/assets/ed45c58d-cd83-4dbb-bf74-69d3ba00a7ab)

After closing:
![Screenshot_20240927-113538](https://github.com/user-attachments/assets/a32c2063-42e3-43ed-b79b-1660b835b063)

**Comment by gemiren** [comment]
I agree that the color line should be removed when the mini player is not displayed. Will fix that asap. Thanks.

**Comment by fredsleeve** [comment]
Closing, fixed in latest beta.
