### ISSUE TITLE
Overflow menu not responsive in "Now playing" 

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#518]
Version: 24.9.27b
This seems most likely related to the fix from issue #511. Could also affect stable release?
The overflow menu in now playing seems not working anymore or only sometimes, see screen recording:
https://c.gmx.net/@334288198261801446/dhys6eyZRKGm-sZY5dqYBw

**Comment by gemiren** [comment]
Nice catch. Fixed in today's beta update.

**Comment by fredsleeve** [comment]
Wow, that was fast. Fixed. Thanks. Closing this one.
