### ISSUE TITLE
Now Playing: Marked as played status and remaining time not correct 

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#519]
Version 24.10.1b

Marked as played status not correct:
1. Make sure the these settings are set:
- Media player > Restart from the beginning > disabled
- Episodes > When pressing an episode in list > Episodes > ask me for action
2. Now set an episode to "mark as played"
4. Go to podcast and open "played" tab
5. Open the previous set "as played" episode with action " Start playing and go to Now Playing"
6. Go to overflow menu and you'll see that the status of the episode is not correct: It shows "Mark episode as played" instead of the other options. Note: If you select "view episode" the played status is correct.

Remaining time not correct:
1. Proceed as in the 1st issue, but make sure you to show the remaining time of the episode instead of the absolute time.
2. If you have marked the episode as played, close the episode in mini player an reopen it with "Start playing and go to Now playing".
3. Have a look at the remaining time: It shows weird times.

**Comment by gemiren** [comment]
That's really a nice catch! Fixed in today's beta update. Thanks!

**Comment by fredsleeve** [comment]
Closing, fixed.
