### ISSUE TITLE
Played and Unplayed tabs not correct 

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#520]
Version 24.10.4b

It looks like the Played/Unplayed tabs of podcast does not load correctly.
1. Open a podast with with played episodes and go to  "played" tab
2. Now return and open another podcast: This will load "unplayed" instead of "played", but shows the played episodes instead.

**Comment by gemiren** [comment]
Nice catch! Fixed in today's beta update. Thanks!

**Comment by fredsleeve** [comment]
Closing, fixed.
