### ISSUE TITLE
[BUG] Top bar not working on the playback screen after switch app

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#522]
I've noticed that the top bar doesn't work on the playback screen if I switch to another app and back to PRA. I've tried changing the playback speed and add the episode to favorites, but the buttons are unresponsive.

**Comment by gemiren** [comment]
Thanks very much for the bug report. Are you using the latest beta version? Theis issue should have been fixed in the latest beta version.

**Comment by kubalav** [comment]
Yes, I'm. Beta version 24.10.4b.

**Comment by fredsleeve** [comment]
Also noticed this bug, thought it was a device related issue.
But it's reproducable, see screen recording:
https://c.gmx.net/@334288198261801446/KCpU1mj-QBW4EZeufnWtbw

**Comment by gemiren** [comment]
Fixed in today's beta update. Thanks!

**Comment by kubalav** [comment]
Fixed!
