### ISSUE TITLE
Question or bug: Option "Remember volume level"

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#525]
Hi,

I am wondering what the Media player option "Remember volume level" does (version 24.10.15R).

My intention is, that this option saves the volume level for a played episode and when increasing e.g. the volume level outside the app, it resets the level to the saved volume of the episode when resume playing. But obviously this isn't case. Instead "Overwrite volume mute state" is working that way.

Can you explain it to me please? Thanks.

**Comment by gemiren** [comment]
'Remember volume level' is intended to save the current volume level and restore to that volume level later.

Say your system volume level is set to 10. You started playing. After playing, you close the app and then lowered the volume level to 5. The next time you start the app to resume the playback, the app will restore the system volume level to 10.

If the current volume is muted then it requires the 'Overwrite volume mute state' option to be enabled at the same time.

**Comment by gemiren** [comment]
I can confirm the 'Remember volume level' option isn't working as described. Will get it fixed ASAP. Thanks.

**Comment by fredsleeve** [comment]
Fixed in latest beta 24.10.21b
