### ISSUE TITLE
Feature request: "natural sort order"

### ISSUE THREAD

**Issue by logixoul** [Podcast-Republic/PRApp#535]
You can see a description of this feature here:
https://en.wikipedia.org/wiki/Natural_sort_order

For example, in one of my "virtual podcasts" (i.e. local file podcasts) I have files like:

- Headway_5e_Beg_SB_5.1.mp3
- Headway_5e_Beg_SB_5.2.mp3
- Headway_5e_Beg_SB_5.3.mp3
- ...
- Headway_5e_Beg_SB_5.10.mp3
- Headway_5e_Beg_SB_5.11.mp3
- Headway_5e_Beg_SB_5.12.mp3

The problem is that Podcast Republic sorts them like this:
- Headway_5e_Beg_SB_5.1.mp3
- Headway_5e_Beg_SB_5.10.mp3
- Headway_5e_Beg_SB_5.11.mp3
- Headway_5e_Beg_SB_5.12.mp3
- Headway_5e_Beg_SB_5.2.mp3
- Headway_5e_Beg_SB_5.3.mp3
- ...

**Comment by gemiren** [comment]
There's no easy way to do this since we don't know the format used for the filename. Since you have the access to the files it's actually easier to rename the files so they can be sorted in natural order. Thanks.

**Comment by logixoul** [comment]
It doesn't need to be difficult to implement.

The cool thing about natural sorting is that (in its most basic form) it's a strictly defined algorithm, not a heuristic. It doesn't require you to know the filename's format.

Here's a MIT licensed implementation in C#:

http://www.interact-sw.co.uk/iangblog/2007/12/13/natural-sorting

When I say "most basic form" I mean "a form that covers 80%-95% of usecases and is strictly better than the usual/naive sorting order". In other words, implementing it has no downsides - it won't break anyone's usecase.

**Comment by gemiren** [comment]
Thanks very much for all the information. Turns out that Kotlin already supports the natural order sorting. This enhancement has been added to the app, and will be in the next update.   You may need to switch to other sorting options and then come back to sort by the filename to get the updated sorting result. Thanks.

**Comment by logixoul** [comment]
Awesome, thanks!

**Comment by logixoul** [comment]
Excuse me, I decided to try this app again, but in version 25.4.13R there still doesn't seem to be any natural sorting.

**Comment by gemiren** [comment]
This feature has been added and is only available for virtual podcasts.

If the list was already sorted before this feature was added then you need to trigger the sorting again to sort the list in the natural order.

**Comment by gemiren** [comment]
That's the expected result from the Kotlin's natural order. You can check that out from this linked example: https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.comparisons/natural-order.html if you remove the string length comparison.
