### ISSUE TITLE
Pause/resume download from list does not work properly

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#538]
Version 24.12.20b

Steps to reproduce:
1. Start downloading an episode
2. Go to "Downloading" tab and hit the pause icon in the list
3. Downloads stops, but tapping on the resume icon does not repsond
4. When switching to another tab and going back to "Downloading" the button works again

Details see screen recording: https://c.gmx.net/@334288198261801446/VH1ft7mKT4yCW3JdKU0MEA

**Comment by gemiren** [comment]
Nice catch. Fixed in today's beta update. Happy holidays!

**Comment by fredsleeve** [comment]
Fixed in 24.12.26b
