### ISSUE TITLE
Multiple messages popping up when swipe to delete is used

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#539]
Version 24.12.20b

Steps to reproduce:
1. Download an episode
2. Use swipe to left to delete the download
3. The action message "When deleting a download" pops up multiple times
4. (This does not happen when using the "context menu" for deleting a download)

For details see screen recording: https://c.gmx.net/@334288198261801446/LPyAJJJoRg-En7_BhdyX9A

**Comment by gemiren** [comment]
Nice catch. Fixed in today's beta update. Happy holidays!

**Comment by fredsleeve** [comment]
Fixed in 24.12.26b
