### ISSUE TITLE
Adding to a playlist doesn't always trigger download

### ISSUE THREAD

**Issue by flowrean** [Podcast-Republic/PRApp#542]
I found a case in which episodes added to a playlist set up to auto-download don't actually start downloading.

Steps to reproduce: create a first playlist that doesn't automatically download episodes and a second playlist that does. Add an episode to the first. Open the first playlist, select the episode and choose 'Add to playlists'. Then deselect the first and select the second playlist. The episode is removed from the first and added to the second playlist, as expected, but it does not download.

I'm on version 24.1.25R.

**Comment by gemiren** [comment]
Thanks very much for your bug report. Please update your app to the latest version in the Play Store. I'm not able to reproduce this issue with the latest app version.
