### ISSUE TITLE
Decimal symbol issue

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#56]
Can you fix decimal symbol according current locale in playback speed dialog?

<details>
<summary>Playback speed</summary>

![playback_speed](https://user-images.githubusercontent.com/37414585/141499445-a955909b-1233-4a34-9bfc-46b9b479c099.jpg)

</details>

**Comment by gemiren** [comment]
Sure. Nice catch!

**Comment by oldman63** [comment]
Perfect in 21.11.15b version
