### ISSUE TITLE
[Suggestion] Localization platform for translating

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#57]
I would welcome translating through localization platform e.g. [Crowdin.com](https://github.com/marketplace/actions/crowdin-action), [Transifex.com](https://github.com/marketplace/actions/github-transifex-actions). This brings a number of positives for translators (translation memory, notifications, suggestions, quality assessment, etc.).

What do you think about this?

**Comment by gemiren** [comment]
I'm sure those platforms work better than the raw strings in xml file. However, it's kind of pricy considering there are not much translation activities going on.

**Comment by kubalav** [comment]
I didn't realize Podcast Republic isn't open source. Such pity.
