### ISSUE TITLE
[Bug] Add Quick speeds issue

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#60]
If I try to add custom playback speed I have to use dot instead comma (when press comma it happens nothing). Fix adding decimal symbol according custom locale.

**Comment by gemiren** [comment]
That's interesting. The speed input method is set to accept decimal number only ```android:inputType="numberDecimal"``` . The soft keyboard does have comma on it so it should accept comma input. I'll dig into it.

**Comment by gemiren** [comment]
Fixed now. Will be in next update.
