### ISSUE TITLE
Virtual Podcast - Delete Played Episode - Not working

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#62]
I created a Virtual Podcast from 136 mp3 files.

The "Delete played episode" option is available in the podcast's own settings.

Where and what delete this feature? Because mp3 files are not deleted from Virtual Podcast source folder.

**Comment by gemiren** [comment]
Do you have **Delayed deletion** option enabled in **app Settings > Downloads**? If **Delayed deletion** is enabled then the deleted virtual episode file will not be removed immediately.

**Comment by oldman63** [comment]
> Do you have **Delayed deletion** option enabled in **app Settings > Downloads**? If **Delayed deletion** is enabled then the deleted virtual episode file will not be removed immediately.

Oh sorry. That was really the problem.

The funcion is working perfect!
