### ISSUE TITLE
Wrong Number of "Playback controls" on Notification

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#65]
Device is Restarted
Android: 11
Version: 21.11.15b
Device language: Hungary
App language: English

Only one "Playback Control" is enabled in Settings

![Screenshot_20211118-144634_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/142427771-c93bf2c5-9ce9-4e55-843e-7ea36d113f5b.jpg)

But the Notifications show three controls!

![Screenshot_20211118-144614_Nova7-2](https://user-images.githubusercontent.com/3171626/142427942-5de41e0c-20ce-4b63-be54-e485fef3cddf.jpg)

**Comment by gemiren** [comment]
The Playback controls option is for the media playback notification.
![Untitled](https://user-images.githubusercontent.com/7810771/142560210-a9a44c51-1534-4c94-8366-fef9357bbe72.png)

**Comment by oldman63** [comment]
> The Playback controls option is for the media playback notification.

Sorry, but I don't understand the answer.

**Comment by gemiren** [comment]
I mean this **Playback controls** option is applied to the playback notification as shown in the screenshot above. When you have something playing you'll have this playback notification on the notification area which you can pull down to view it. You can also view the same playback notification on the lock screen.

**Comment by oldman63** [comment]
> I mean this **Playback controls** option is applied to the playback notification as shown in the screenshot above. When you have something playing you'll have this playback notification on the notification area which you can pull down to view it. You can also view the same playback notification on the lock screen.

Okay, I understand. Sorry.
