### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#67]
After modified the "Settings / Downloads / Download location" in the pop-up window:

**Move all files from %1 to the new download directory %2?**

This string is not found in **values\strings.xml**

![Screenshot_20211124-162616_Podcast Republic-2](https://user-images.githubusercontent.com/3171626/143268792-a3bf3a1b-9860-4fe6-bfe0-4a7fd70194c1.jpg)

**Comment by gemiren** [comment]
Added. Thanks.
