### ISSUE TITLE
Confirmation dialog for change volume level needed

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#68]
I use custom volume level for every podcast. I tried to adjust volume and I changed volume for all podcast by mistake.
I suggest to add confirmation dialog for change volume level for all podcasts.

**Comment by gemiren** [comment]
Just curious how do you set custom volume level for every podcast?

**Comment by kubalav** [comment]
I meant audio level boost and Apply to all podcasts/Apply to current podcast buttons.

**Comment by gemiren** [comment]
Added in today's beta update. Thanks.
