### ISSUE TITLE
Problematic AMOLED theme

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#69]
Samsung S10+ with AMOLED display

Settings / User Interface / Theme / AMOLED Black
I think it's problematic

![Screenshot_20211129-153833_Podcast Republic](https://user-images.githubusercontent.com/3171626/143898136-ed2399d7-300a-44f5-949d-aace6212444b.jpg)

Theme / Dark

![Screenshot_20211129-153914_Podcast Republic](https://user-images.githubusercontent.com/3171626/143898220-53884f90-dddf-4785-b112-aeda5b12bff8.jpg)

**Comment by gemiren** [comment]
Are you able to reproduce the bug? I set the theme to AMOLED black but couldn't reproduce this bug. Here is my screen recording https://www.dropbox.com/s/vof1faudwwepsz4/amoled_black_theme.webm?dl=0.

**Comment by oldman63** [comment]
Sorry, unfortunately i can't reproduce the problem

**Comment by gemiren** [comment]
No worries. Hopefully that's just a one-time issue. Thanks.
