### ISSUE TITLE
[feature request] Play downloading episode

### ISSUE THREAD

**Issue by kubalav** [Podcast-Republic/PRApp#9]
By default, if you start playing an episode which is downloading the app will start streaming. I suggest to add an option to start playing local file while is currently downloading.

**Comment by gemiren** [comment]
The app doesn't play partial download. The consideration is that you may not be able to play the full content if network is not available or streaming with data option is not enabled. IMHO, that will be a bad UX design to cut off in the middle. However, I agree that if you do have network connected or streaming with data option enabled it should start playing the partial download first and then start streaming. Will add this to the future updates. Thanks.
